### PR TITLE
[JENKINS-62014] Add retainEnv step to filter environment

### PR DESCRIPTION
**Pull request by daniel-beck**
Co-authored-by: Wadeck Follonier <wadeck.follonier@gmail.com>

---

[JENKINS-62014](https://issues.jenkins-ci.org/browse/JENKINS-62014).

Not quite the same as https://github.com/jenkinsci/jenkins/pull/4683 since this filters only what is provided from Jenkins; would probably need to patch the specific `workflow-durable-task-step`'s to drop the system provided environment.

I plan to still update the UI a bit, perhaps make it more similar to core's (one-line text field with whitespace separated values rather than multi-line text field with newline separated values), TBD. The basics should be done. I may force-push over this.

### CODE REVIEW

**Comment by daniel-beck** [comment]
```
[2020-05-13T13:57:15.151Z] [INFO] --- spotbugs-maven-plugin:3.1.12.2:spotbugs (spotbugs) @ workflow-basic-steps ---
[2020-05-13T13:57:33.299Z] [INFO] Fork Value is true
[2020-05-13T13:57:36.573Z]      [java] [thread 9320 also had an error]
[2020-05-13T13:57:36.573Z]      [java] [thread 14568 also had an error]
[2020-05-13T13:57:36.573Z]      [java] [error occurred during error reporting (null), id 0xc0000005]
[2020-05-13T13:57:36.573Z]      [java] #
[2020-05-13T13:57:36.573Z]      [java] # There is insufficient memory for the Java Runtime Environment to continue.
[2020-05-13T13:57:36.573Z]      [java] # Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool::allocate
[2020-05-13T13:57:36.573Z]      [java] # An error report file with more information is saved as:
[2020-05-13T13:57:36.573Z]      [java] # C:\Users\jenkins\Work\workspace\rkflow-basic-steps-plugin_PR-115\hs_err_pid17808.log
[2020-05-13T13:57:36.573Z]      [java] [error occurred during error reporting , id 0xe0000001]
```

😭

**Comment by dwnusbaum** [comment]
@daniel-beck Any thoughts on putting the new step into https://github.com/jenkinsci/generic-environment-filters-plugin instead since it seems like this is another user-facing feature related to JENKINS-62014? In general, I would prefer to avoid adding new steps to this plugin.

**Comment by daniel-beck** [comment]
@dwnusbaum Sure, I can do that, or a new plugin for this step 👍

**Comment by dwnusbaum** [comment]
@daniel-beck Ok, FWIW, I am not completely against adding it here if you think this is the best place for it, it just seemed like it might be nice to have all of the related features in the same plugin.

**Comment by jglick** [comment]
Also see https://github.com/jenkinsci/generic-environment-filters-plugin/pull/3

**Comment by jglick** [comment]
FTR

> a new plugin for this step

https://github.com/jenkinsci/pipeline-keepenv-step-plugin/

**Pull request closed without merging**
