### PR TITLE
Mention the default units for the timeout step.

### PR DESCRIPTION
**Pull request by mostynb**
src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStep.java uses
'MINUTES' as the default units.

Also, improved the language slightly.

### CODE REVIEW

**Comment by mostynb** [comment]
I guess this is a duplicate of:
https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/13

**Comment by mostynb** [comment]
It is not clear to me what changes you're requesting...

**Comment by jglick** [comment]
Probably easiest for me to file my own PR for it.

**Comment by mostynb** [comment]
If you provide some more details (maybe we could add a contributing.md?) then it might be easier for other people to help you out more.

**Comment by abayer** [comment]
so what @jglick was saying on #13 is that there should be separate `help` html files for the individual parameters - i.e., `help-unit.html` and `help-time.html`. That'll result in the snippet generator showing the help button alongside the parameters, rather than just for the entire step.

**Comment by dwnusbaum** [comment]
See https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/114.

**Pull request closed without merging**
