### PR TITLE
Update plugin POM and BOM

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Set up Dependabot?

**Comment by timja** [comment]
@jenkinsci/workflow-basic-steps-plugin-developers  / @oleg-nenashev are you able to get someone to help with this?

**Review by car-roll — APPROVED** [review]

**Comment by car-roll** [comment]
ah whoops, looks like i don't have write access to this plugin

**Comment by dwnusbaum** [comment]
@car-roll You should have access now

**Pull request merged**
