### PR TITLE
Add exception name in TimeoutStep help

### PR DESCRIPTION
**Pull request by alkuzad**
Using `Exception` is not best idea, better to catch this specific exception

### CODE REVIEW

**Comment by svanoort** [comment]
@dwnusbaum Yeah, I can understand being a little skeezed out by the implementation-specific version -- after doing some digging and some thought, I think it's okay here, and here's why:

* If you catch generic InterruptedException you can catch legitimate attempts to interrupt the thread or flow
* FlowInterruptedException is more specific than the generic exception someone might catch, which can result in catching things you might want to bubble up (more serious internal errors)

**Comment by svanoort** [comment]
Thanks for the contribution, @alkuzad

**Comment by jglick** [comment]
User scripts should not be referring to `FlowInterruptedException` explicitly. If there is a particular use case for `catch`ing discriminated exception types which might include Jenkins-specific types, this would be better handled by a new step, something akin to `catchError` I suppose.

**Comment by jglick** [comment]
IOW, I guess a -0 on this. Fine to document what the behavior is in principle, but in this case the _presence_ of the documentation implies that you should be doing something which you should not.

**Comment by alkuzad** [comment]
@jglick 

input was not designed as if/else but rather go/no-go tool
timeout was explictly designed as "after this time, build is screwed, abort" tool, not "maximum wait time"

yet, 2 try/catch later, they are changed to bow to management will :D

Clean way of doing this would be to create two new steps with desired behaviour and use them instead. However I lack Java skill and proper IDE to do such things, going around this problem with plain groovy was a lot easier.

**Pull request merged**
