### PR TITLE
[JENKINS-59776] Add quiet option to waitUntil

### PR DESCRIPTION
**Pull request by bawjensen**
I did my best to adhere to existing patterns. I'm assuming this feature is relatively uncontroversial given the lack of discussion on [the related ticket](https://issues.jenkins-ci.org/browse/JENKINS-59776).

### CODE REVIEW

**Comment by shaybc** [comment]
why this obviously "should have been out of the box" feature hasn't been accepted for merge?
do i need to develop yet another class just to fix Jenkins bad UX ?

**Comment by bawjensen** [comment]
@dwnusbaum @bitwiseman what comes next, in regards to including this in a future release?

**Comment by bitwiseman** [comment]
@bawjensen 
Sorry for the delay. 

@dwnusbaum
It looks like I don't have merge or release permissions here.

**Comment by bawjensen** [comment]
@bitwiseman just checking in, have your merge/release permissions been sorted or are we still waiting on that?

**Comment by bawjensen** [comment]
@dwnusbaum appreciate the PR, it's merged and it looks like this PR got updated appropriately as well

**Comment by tempora-mutantur** [comment]
Hi.

Thank you for the option.
I have one more thing that would make it better for us

If you set "quiet" in true, you'll still have lots of lines inside the console log that look like

[Pipeline] }
[Pipeline] {
[Pipeline] }
[Pipeline] {
[Pipeline] }
[Pipeline] {
[Pipeline] }
[Pipeline] {
[Pipeline] }
[Pipeline] {
[Pipeline] }
[Pipeline] {
[Pipeline] }

Can we avoid it while using the option?
Thank you.

**Comment by puetzk** [comment]
and likewise, it still really spams up the flowGraphTable "Pipeline Steps" view with these blocks

**Comment by bitwiseman** [comment]
@tempora-mutantur @puetzk 
Please open a new issue for this.  Comments on closed PR get lost extremely quickly.

**Comment by tempora-mutantur** [comment]
@bitwiseman 
Thank you, created this issue

https://issues.jenkins-ci.org/browse/JENKINS-62531

**Pull request merged**
