### PR TITLE
Ignore eclipse configuration files

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@oleg-nenashev why this repo nobody review.

**Comment by oleg-nenashev** [comment]
It depends on the plugin maintainers. Not all of them are really active.
Use @jenkinsci/code-reviewers is such case

**Comment by LinuxSuRen** [comment]
So the review team is very important, when the owner no longer active or care it.

**Comment by oleg-nenashev** [comment]
Yes, that's what we are trying to do, more or less successfully

**Comment by LinuxSuRen** [comment]
In order to let more and more Chinese people use Jenkins, I will translate all English to Chinese step and step.

**Pull request merged**
